### ISSUE TITLE
Sieverules

### ISSUE THREAD

**Issue by arodier** [corbosman/dovecot_impersonate#1]
Hello,

Whe I am using the sieverules plugin for roundcube with impersonate, I have a sieve authentication error.
Could you make your plugin compatibe with the sieverules plugin for roundcube, please?
You may have to implement a hook in your plugin.

See https://github.com/JohnDoh/Roundcube-Plugin-SieveRules-Managesieve#sieverules_connect-hook

Kind regards,
André

**Comment by corbosman** [comment]
I dont have sieverules to test this. It probably works if you just add the sieverules hook like the managesieve hook. Feel free to send me a pull request.

**Comment by korylprince** [comment]
I have been using sieverules and impersonate together for several months. Here's what I did.

**Add the plugins to main.inc.php:**
sieverules,dovecot_impersonate (in that order - it matters)

**In sieverules configuration:**
change host/port to localhost/4190

change sieverules_auth_cid/pw to my master user credentials for dovecot

change default file and example file to NULL (not needed I don't think, but just to list all changes)

That's really it. Verify, of course, that your master user is actually working with dovecot by using imap directly.

**Comment by arodier** [comment]
Just finding this, perhaps I can close this, now
